const userTypes ={
    EMAIL_SIGNIN_START : 'EMAIL_SIGNIN_START',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    CHECK_USER_SESSION : 'CHECK_USER_SESSION ',
    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
    SIGNUP_USER_START: 'SIGNUP_USER_START',
    SIGNUP_USER_SUCCESS:'SIGNUP_USER_SUCCESS',
    GOOGLE_SIGNIN_START:'GOOGLE_SIGNIN_START',
    RESET_PASSWORD_START : 'RESET_PASSWORD_START',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    USER_ERROR:'USER_ERROR',
    RESET_USER_STATE: 'RESET_USER_STATE'
}

export default userTypes;